name: CMake
on: [push, pull_request]
env:
  TERM: xterm-256color
  GTEST_COLOR: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # Don't abort on push to avoid incomplete coveralls uploads
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        include:

            # Only ASAN is valid in Windows MSVC
            # So don't test Undefined,Thread or Memory
            # See https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170
          - name: Windows MSVC ASAN
            os: windows-latest
            compiler: cl
            cmake-args: -DWITH_SANITIZER=Address -A x64
            build-config: Debug
            # codecov disabled for msvc


    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        show-progress: false

    - name: Checkout test corpora
      uses: actions/checkout@v6
      # Don't test against all corpora with MinGW due to Wine being unable to run parallel jobs
      # without connection timeout. Without parallel jobs test runs using Wine take close to an hour.
      # Also don't test the extra corpora with Sanitizer builds or RISC-V or e2k, due to their slow testing.
      if: ${{ !contains(matrix.name, 'MinGW') && !contains(matrix.name, 'RISC-V') && !contains(matrix.name, 'e2k') && !contains(matrix.cmake-args, 'WITH_SANITIZER') }}
      with:
        repository: zlib-ng/corpora
        path: test/data/corpora
        show-progress: false

    - name: Add repositories (Wine)
      if: contains(matrix.packages, 'wine32')
      run: sudo dpkg --add-architecture i386

    - name: Add ubuntu mirrors
      if: runner.os == 'Linux' && !contains(matrix.os, 'z15')
      # Github Actions caching proxy is at times unreliable
      run: |
        echo -e 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | sudo tee /etc/apt/mirrors.txt
        curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
        sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu/#mirror+file:/etc/apt/mirrors.txt#' /etc/apt/sources.list

    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux' && !contains(matrix.os, 'z15')
      run: |
        sudo apt-get update
        sudo apt-get install -y --allow-downgrades --no-install-recommends \
            ${{ matrix.packages || 'libgtest-dev libbenchmark-dev' }}

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        # strawberryperl installs /c/Strawberry/c/bin/libstdc++-6.dll, which is incompatible with the mingw64 one.
        # zlib-ng does not need perl, so simply remove it.
        choco uninstall --no-progress strawberryperl
        choco install --no-progress ninja ${{ matrix.packages }}

    - name: Install Visual Studio toolset v140 (Windows)
      if: contains(matrix.name, 'v140')
      run: |
        # Windows 10 SDK (10.0.14393.795)
        # https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/index-legacy
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=838916 -OutFile sdksetup.exe -UseBasicParsing
        Unblock-File sdksetup.exe
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off", "/features OptionId.WindowsSoftwareDevelopmentKit"

        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToInstall= @(
          "Microsoft.VisualStudio.Component.VC.140"
        )
        [string]$workloadArgs = $componentsToInstall | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

    - name: Install Visual Studio toolset v141 (Windows)
      if: contains(matrix.name, 'v141')
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToInstall= @(
          "Microsoft.VisualStudio.Component.VC.v141.x86.x64"
        )
        [string]$workloadArgs = $componentsToInstall | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

    - name: Install Windows 11 SDK (ARM)
      if: contains(matrix.name, 'MSVC ARM ')
      run: |
        # Windows 11 SDK (10.0.22621.2428)
        # https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/index-legacy
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=2250105 -OutFile sdksetup.exe -UseBasicParsing
        Unblock-File sdksetup.exe
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/ceip off"

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      run: brew install ninja ${{ matrix.packages }}
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - name: Install Emscripten
      if: contains(matrix.name, 'WASM32')
      uses: mymindstorm/setup-emsdk@v14

    # Get MCST LCC from github actions cache or download from dev.mcst.ru and save to cache
    - name: Cache MCST LCC ${{ matrix.toolchain }} (Ubuntu)
      if: contains(matrix.name, 'e2k')
      id: cache-lcc
      uses: actions/cache@v5
      with:
        path: /opt/mcst
        key: cache-lcc-${{ matrix.toolchain }}

    - name: Install MCST LCC ${{ matrix.toolchain }} (Ubuntu)
      if: contains(matrix.name, 'e2k') && steps.cache-lcc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://dev.mcst.ru/downloads/2025-06-27/cross-sp-${{ matrix.toolchain }}_64.tgz
        sudo tar -xzf cross-sp-${{ matrix.toolchain }}_64.tgz -C /
        rm -f cross-sp-${{ matrix.toolchain }}_64.tgz

    # Get qemu-e2k-static from github actions cache or download from dev.mcst.ru and save to cache
    - name: Cache MCST QEMU (Ubuntu)
      if: contains(matrix.name, 'e2k')
      id: cache-qemu-e2k-static
      uses: actions/cache@v5
      with:
        path: /usr/local/bin/qemu-e2k-static
        key: cache-qemu-e2k-static-20251226

    - name: Install MCST QEMU (Ubuntu)
      if: contains(matrix.name, 'e2k') && steps.cache-qemu-e2k-static.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://dev.mcst.ru/downloads/2025-12-26/qemu-e2k-static
        chmod +x qemu-e2k-static
        sudo mv qemu-e2k-static /usr/local/bin

    - name: Initialize Wine
      # Prevent parallel test jobs from initializing Wine at the same time
      if: contains(matrix.packages, 'wine')
      run: wineboot --init

    - name: Compile LLVM C++ libraries (MSAN)
      if: contains(matrix.name, 'MSAN')
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project --single-branch --branch release/20.x
        cmake -S llvm-project/runtimes -B llvm-project/build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
          -DLLVM_USE_SANITIZER=MemoryWithOrigins \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXX_INCLUDE_BENCHMARKS=OFF \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_DOCS=OFF
        cmake --build llvm-project/build -j3 -- cxx cxxabi
        echo "LLVM_BUILD_DIR=`pwd`/llvm-project/build" >> $GITHUB_ENV
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}

    - name: Generate project files
      shell: bash
      # Shared libraries turned off for qemu ppc* and sparc & reduce code coverage sources
      run: |
        cmake -S . ${{ matrix.cmake-args }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-config || 'Release' }} \
          -DBUILD_SHARED_LIBS=${{ matrix.build-shared || 'OFF' }} \
          -DWITH_FUZZERS=ON \
          -DWITH_MAINTAINER_WARNINGS=ON \
          ${{ matrix.codecov && '-DWITH_CODE_COVERAGE=ON' }}
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}
        CFLAGS: ${{ matrix.cflags }}
        CXXFLAGS: ${{ matrix.cxxflags }}
        LDFLAGS: ${{ matrix.ldflags }}
        CI: true

    - name: Compile source code
      run: cmake --build . --verbose -j2 --config ${{ matrix.build-config || 'Release' }}

    - name: Run test cases
      # Don't run tests on Windows ARM
      if: runner.os != 'Windows' || contains(matrix.name, 'ARM') == false
      run: ctest --extra-verbose --debug -C ${{ matrix.build-config || 'Release' }} -E benchmark_zlib --output-on-failure --max-width 120 -j ${{ matrix.parallels-jobs || '3' }}
      env:
        ASAN_OPTIONS: ${{ matrix.asan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        MSAN_OPTIONS: ${{ matrix.msan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        TSAN_OPTIONS: ${{ matrix.tsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        LSAN_OPTIONS: ${{ matrix.lsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
        UBSAN_OPTIONS: ${{ matrix.ubsan-options || 'verbosity=0' }}:print_stacktrace=1:abort_on_error=1:halt_on_error=1

    - name: Generate coverage report
      if: matrix.codecov
      shell: bash
      run: |
        python3 -u -m venv ./venv
        source ./venv/${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}/activate
        python3 -u -m pip install gcovr
        python3 -m gcovr -j 3 --gcov-ignore-parse-errors --verbose \
          --exclude '(.*/|^)(_deps|benchmarks)/.*' \
          --exclude-unreachable-branches \
          --merge-mode-functions separate \
          --merge-lines \
          --gcov-executable "${{ matrix.gcov-exec || 'gcov' }}" \
          --xml --output ${{ matrix.codecov }}.xml

#     - name: Upload coverage report artifact
#       uses: actions/upload-artifact@v6
#       if: matrix.codecov
#       with:
#         name: ${{ matrix.name }} (coverage)
#         path: ${{ matrix.codecov }}.xml
#         retention-days: 1
#
#     - name: Upload job coverage report to coveralls
#       uses: coverallsapp/github-action@v2
#       if: (matrix.codecov && !contains(matrix.os, 'z15') && (env.COVERALLS_REPO_TOKEN != '' || github.repository == 'zlib-ng/zlib-ng'))
#       with:
#         file: ${{ matrix.codecov }}.xml
#         flag-name: "${{ matrix.name }}-${{ github.event_name }}"
#         parallel: true
#       env:
#         COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
#
#     - name: Test benchmarks (crashtest only, no coverage data collection)
#       if: contains(matrix.cmake-args, '-DWITH_BENCHMARKS=ON')
#       run: ctest --verbose -C Release -R ^benchmark_zlib$ --output-on-failure --max-width 120 -j ${{ matrix.parallels-jobs || '3' }}
#       env:
#         ASAN_OPTIONS: ${{ matrix.asan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
#         MSAN_OPTIONS: ${{ matrix.msan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
#         TSAN_OPTIONS: ${{ matrix.tsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
#         LSAN_OPTIONS: ${{ matrix.lsan-options || 'verbosity=0' }}:abort_on_error=1:halt_on_error=1
#         UBSAN_OPTIONS: ${{ matrix.ubsan-options || 'verbosity=0' }}:print_stacktrace=1:abort_on_error=1:halt_on_error=1
#
#     - name: Upload build errors
#       uses: actions/upload-artifact@v6
#       if: failure()
#       with:
#         name: ${{ matrix.name }} (cmake)
#         path: |
#           **/CMakeFiles/CMakeOutput.log
#           **/CMakeFiles/CMakeError.log
#           **/Testing/Temporary/*
#           coverage.xml
#         retention-days: 30
#
#   coverage:
#     name: Upload Coverage Reports
#     runs-on: ubuntu-latest
#     needs: cmake
#     if: cancelled() == false
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v6
#       with:
#         show-progress: false
#
#     - name: Download all reports
#       uses: actions/download-artifact@v7
#       with:
#         merge-multiple: true
#
#     - name: Display all coverage artifacts
#       run: |
#         ls -R *.xml
#         echo "COVERAGE_REPORTS=`ls -p *.xml | grep -v / | tr '\n' ',' | sed 's/,$//g'`" >> $GITHUB_ENV
#
#     - name: Upload reports to codecov
#       uses: codecov/codecov-action@v5
#       if: (env.CODECOV_TOKEN != '' || github.repository == 'zlib-ng/zlib-ng')
#       with:
#         files: ${{ env.COVERAGE_REPORTS }}
#         name: "cmake-umbrella-${{ github.event_name }}"
#         verbose: true
#         fail_ci_if_error: true
#       env:
#         CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
#
#     - name: Upload to Coveralls - Final
#       uses: coverallsapp/github-action@v2
#       if: (env.COVERALLS_REPO_TOKEN != '' || github.repository == 'zlib-ng/zlib-ng')
#       with:
#         parallel-finished: true
#       env:
#         COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
